Repository Netcracker/qubership-envgene, pull requests merged in 2025-06, with the labels that each got.

#264 Feature/issue 247 on commit build
  .github/workflows/docker-build-instance-repo-pipeline.yml
  .github/workflows/docker-build-qubership-effective-set-generator.yml
  .github/workflows/docker-build-qubership-envgene.yml
  .github/workflows/docker-build-qubership-gcip.yml
  .github/workflows/pr-conventional-commits.yaml
Labels: enhancement

#250 fix: add schema description
  schemas/application.schema.json
  schemas/cloud.schema.json
  schemas/config.schema.json
  schemas/effectiveset.schema.json
  schemas/env-definition.schema.json
  schemas/env-specific-resource-profile.schema.json
  schemas/integration.schema.json
  schemas/namespace.schema.json
  schemas/paramset.schema.json
  schemas/resource-profile.schema.json
  schemas/tenant.schema.json
  scripts/build_env/main.py
  test_data/test_environments/cluster-01/env-01/cloud.yml
  test_data/test_environments/cluster-01/env-02/cloud.yml
  test_data/test_environments/cluster-01/env-03/cloud.yml
  test_data/test_environments/cluster-01/env-04/cloud.yml
  test_data/test_environments/cluster01/env01/cloud.yml
  test_data/test_environments/cluster01/env03/cloud.yml
  test_data/test_environments/cluster01/env04/cloud.yml
  test_data/test_templates/env_templates/test-template-1/cloud.yml.j2
  test_data/test_templates/env_templates/test-template-2/cloud.yml.j2
Labels: bug, enhancement

#294 docs: refactor template macros and fix minor md issues
  README.md
  docs/basic-how-to.md
  docs/env-specific-schema.md
  docs/envgene-configs.md
  docs/template-macros.md
  samples/README.md
Labels: documentation
