Repository Netcracker/qubership-envgene, pull requests merged in 2025-08, with the labels that each got.

#472 feat: Added CRED ROTATION
  .gitignore
  build_effective_set_generator/scripts/test_generate_effective_set.py
  build_envgene/ansible/roles/build_env/tasks/02_prepare_vars.yaml
  build_envgene/ansible/roles/build_env/tasks/02_prepare_vars_new.yaml
  build_envgene/ansible/roles/build_env/tasks/03_upload_template.yaml
  build_envgene/build/Dockerfile
  build_envgene/build/constraint.txt
  build_envgene/build/pip.conf
  build_envgene/build/requirements.txt
  build_envgene/build/sources.list
  build_envgene/build/sources_ubuntu.list
  build_envgene/scripts/git_commit.sh
  build_gcip/scripts/credential_rotation_job.py
  build_gcip/scripts/env_build_jobs.py
  build_gcip/scripts/github_actions.py
  build_gcip/scripts/gitlab_ci.py
  build_gcip/scripts/main.py
  build_gcip/scripts/pipeline_parameters.py
  creds_rotation/build/requirements.txt
  creds_rotation/scripts/core_rotation.py
  creds_rotation/scripts/creds_rotation_handler.py
  creds_rotation/scripts/models.py
  creds_rotation/scripts/utils/cred_utils.py
  creds_rotation/scripts/utils/error_constants.py
  creds_rotation/scripts/utils/file_utils.py
  creds_rotation/scripts/utils/search_utils.py
  creds_rotation/scripts/utils/yaml_utils.py
  docs/envgene-objects.md
  docs/error-catalog.md
  docs/features/cred-rotation.md
  docs/images/cred-affection.png
  docs/instance-pipeline-parameters.md
  docs/template-macros.md
  docs/test-cases/cred-rotation.md
  github_workflows/instance-repo-pipeline/.github/actions/download_artifact/action.yml
  github_workflows/instance-repo-pipeline/.github/docs/PIPELINE_USAGE_GUIDE.md
  github_workflows/instance-repo-pipeline/.github/pipeline_vars.yaml
  github_workflows/instance-repo-pipeline/.github/scripts/load_env_variables.py
  github_workflows/instance-repo-pipeline/.github/scripts/process_api_input.py
  github_workflows/instance-repo-pipeline/.github/vars.yaml
  github_workflows/instance-repo-pipeline/.github/workflows/pipeline.yml
  python/envgene/envgenehelper/errors.py
Labels: documentation

#478 Feature/auto environment name derivation
  docs/envgene-configs.md
  docs/features/auto-env-name-derivation.md
  docs/features/env-inventory-generation.md
  docs/test-cases/auto-environment-name.md
  docs/use-cases/README.md
  docs/use-cases/auto-environment-name.md
Labels: bug, documentation

#523 fix: add missing function for cred_rotation feature
  python/envgene/envgenehelper/crypt.py
Labels: bug

#516 docs: add ns filter feature
  .github/workflows/cla.yaml
  CODEOWNERS
  docs/envgene-objects.md
  docs/features/namespace-render-filtering.md
  docs/instance-pipeline-parameters.md
  docs/template-macros.md
Labels: documentation

#528 feat: Updating the logic for version update
  .github/actions/build-effective-set-python/action.yml
  .github/actions/build-effective-set/action.yml
  .github/actions/build-envgene/action.yml
  .github/actions/build-gcip/action.yml
  .github/actions/build-pipeline/action.yml
  .github/actions/generate-docker-tags/action.yml
  .github/workflows/dev-build-docker-images.yml
  .github/workflows/docker_publish_release.yml
  .github/workflows/perform_tests.yml
  github_workflows/instance-repo-pipeline/.github/workflows/pipeline.yml
Labels: enhancement

#535 fix: Update Dockerfile
  build_envgene/build/Dockerfile
Labels: bug
