Repository Netcracker/qubership-envgene, pull requests merged in 2025-09, with the labels that each got.

#628 feat: add ability to configure gitlab runner timeout via RUNNER_SCRIPT_TIMEOUT
  build_pipegene/scripts/pipeline_helper.py
  build_pipegene/scripts/pipeline_parameters.py
  docs/envgene-repository-variables.md
Labels: bug, documentation, enhancement

#638 fix: clean up resulting dir by exclude list
  scripts/build_env/main.py
  scripts/build_env/test_render_envs.py
Labels: bug

#645 feat: Update the tag insert to pipeline, updated the logic to publish the release.
  .github/workflows/dev-build-docker-images.yml
  .github/workflows/docker_publish_release.yml
  github_workflows/instance-repo-pipeline/.github/workflows/pipeline.yml
Labels: enhancement

#652 docs: Add Registry Definition v2 docs
  docs/envgene-objects.md
  examples/registry-definition-v2.yml
  schemas/regdef-v2.schema.json
Labels: documentation

#659 feat: Added new version of instance pipeline
  github_workflows/instance-repo-pipeline/.github/scripts/collect_all_vars.py
  github_workflows/instance-repo-pipeline/.github/workflows/pipeline-v1.yml
  github_workflows/instance-repo-pipeline/.github/workflows/pipeline.yml
Labels: enhancement

#661 feat: Updated scripts and upload artifact action in instance pipeline
  github_workflows/instance-repo-pipeline/.github/scripts/unified_variable_exporter.sh
  github_workflows/instance-repo-pipeline/.github/workflows/pipeline.yml
Labels: enhancement

#662 feat: Updated the pr-auto-labeler
  .github/auto-labeler-config.yaml
  .github/workflows/automatic-pr-labeler.yaml
  CODEOWNERS
Labels: enhancement

#666 fix: No SBOMs mode of ES calculation
  build_effective_set_generator_java/commons/src/main/java/org/qubership/cloud/devops/commons/service/interfaces/RegistryConfigurationService.java
  build_effective_set_generator_java/effective-set-generator/src/main/java/org/qubership/cloud/devops/cli/CmdbCli.java
  build_effective_set_generator_java/effective-set-generator/src/main/java/org/qubership/cloud/devops/cli/parser/CliParameterParser.java
  build_effective_set_generator_java/effective-set-generator/src/main/java/org/qubership/cloud/devops/cli/pojo/dto/input/InputData.java
  build_effective_set_generator_java/effective-set-generator/src/main/java/org/qubership/cloud/devops/cli/pojo/dto/shared/EffectiveSetVersion.java
  build_effective_set_generator_java/effective-set-generator/src/main/java/org/qubership/cloud/devops/cli/pojo/dto/shared/SharedData.java
  build_effective_set_generator_java/effective-set-generator/src/main/java/org/qubership/cloud/devops/cli/repository/implementation/FileDataConverterImpl.java
  build_effective_set_generator_java/effective-set-generator/src/main/java/org/qubership/cloud/devops/cli/repository/implementation/FileDataRepositoryImpl.java
  build_effective_set_generator_java/effective-set-generator/src/main/java/org/qubership/cloud/devops/cli/service/implementation/RegistryConfigurationServiceImpl.java
  build_effective_set_generator_java/effective-set-generator/src/main/java/org/qubership/cloud/devops/cli/utils/BomReaderUtilsImpl.java
  build_effective_set_generator_java/effective-set-generator/src/main/java/org/qubership/cloud/devops/cli/utils/FileSystemUtils.java
  github_workflows/instance-repo-pipeline/.github/workflows/pipeline.yml
Labels: bug

#673 docs: doc calc update
  CODEOWNERS
  docs/calculator-cli.md
Labels: documentation

#672 fix: creating empty files without parameters
  build_effective_set_generator_java/effective-set-generator/src/main/java/org/qubership/cloud/devops/cli/parser/CliParameterParser.java
  build_effective_set_generator_java/effective-set-generator/src/main/java/org/qubership/cloud/devops/cli/repository/implementation/FileDataConverterImpl.java
  github_workflows/instance-repo-pipeline/.github/workflows/pipeline.yml
Labels: bug
